// v3.31.0: testes do storage de plantas. Magic bytes + tamanho + hash + paths.

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
  validarMagicBytes,
  validarTamanho,
  calcularSha256,
  caminhoRelativo,
  salvarPlanta,
  lerPlanta,
  removerPlanta,
  LIMITES_BYTES,
} from './quadraPlantaStorage';

const TMP = path.join(os.tmpdir(), `qpstorage-test-${Date.now()}`);
process.env.STORAGE_ROOT = TMP;

beforeAll(async () => {
  await fs.promises.mkdir(TMP, { recursive: true });
});
afterAll(async () => {
  await fs.promises.rm(TMP, { recursive: true, force: true });
});

describe('quadraPlantaStorage — validarMagicBytes', () => {
  it('1. PDF valido: header %PDF- -> ok', () => {
    const buf = Buffer.from('%PDF-1.7\n%fakecontent');
    expect(() => validarMagicBytes(buf, 'pdf')).not.toThrow();
  });
  it('2. PDF invalido (sem header) -> throw', () => {
    const buf = Buffer.from('NOT_A_PDF\n');
    expect(() => validarMagicBytes(buf, 'pdf')).toThrow(/PDF invalido/);
  });
  it('3. DXF ASCII valido: header "0\\nSECTION" -> ok', () => {
    const buf = Buffer.from('0\nSECTION\n2\nHEADER\n');
    expect(() => validarMagicBytes(buf, 'dxf')).not.toThrow();
  });
  it('4. DXF com tag "AutoCAD" no header -> ok (Metatopo gera assim)', () => {
    const buf = Buffer.from('999\nDXF generated by AutoCAD\n0\nSECTION\n');
    expect(() => validarMagicBytes(buf, 'dxf')).not.toThrow();
  });
  it('5. DXF invalido -> throw', () => {
    const buf = Buffer.from('not a dxf at all');
    expect(() => validarMagicBytes(buf, 'dxf')).toThrow(/DXF invalido/);
  });
  it('6. DWG com magic AC1024 -> ok', () => {
    const buf = Buffer.concat([Buffer.from('AC1024', 'ascii'), Buffer.alloc(100)]);
    expect(() => validarMagicBytes(buf, 'dwg')).not.toThrow();
  });
  it('7. DWG com magic AC1032 -> ok (versao 2018)', () => {
    const buf = Buffer.concat([Buffer.from('AC1032', 'ascii'), Buffer.alloc(100)]);
    expect(() => validarMagicBytes(buf, 'dwg')).not.toThrow();
  });
  it('8. DWG sem magic -> throw', () => {
    const buf = Buffer.alloc(100);
    expect(() => validarMagicBytes(buf, 'dwg')).toThrow(/DWG invalido/);
  });
});

describe('quadraPlantaStorage — validarTamanho', () => {
  it('9. DXF 51MB excede limite (50MB)', () => {
    const buf = Buffer.alloc(LIMITES_BYTES.dxf + 1);
    expect(() => validarTamanho(buf, 'dxf')).toThrow(/DXF excede/);
  });
  it('10. PDF 31MB excede limite (30MB)', () => {
    const buf = Buffer.alloc(LIMITES_BYTES.pdf + 1);
    expect(() => validarTamanho(buf, 'pdf')).toThrow(/PDF excede/);
  });
  it('11. PDF 1KB cabe no limite', () => {
    expect(() => validarTamanho(Buffer.alloc(1024), 'pdf')).not.toThrow();
  });
});

describe('quadraPlantaStorage — hash + paths', () => {
  it('12. SHA-256 deterministico para mesmo buffer', () => {
    const buf = Buffer.from('conteudo fixo');
    const h1 = calcularSha256(buf);
    const h2 = calcularSha256(buf);
    expect(h1).toBe(h2);
    expect(h1.length).toBe(64); // hex SHA-256 = 64 chars
  });
  it('13. caminhoRelativo usa forward slash (cross-platform)', () => {
    const p = caminhoRelativo(123, 456, 'dxf');
    expect(p).toBe('loteamentos/123/quadras/456/planta.dxf');
    expect(p).not.toContain('\\');
  });
});

describe('quadraPlantaStorage — salvar/ler/remover (filesystem real)', () => {
  it('14. salvarPlanta grava arquivo e retorna metadados', async () => {
    const buf = Buffer.from('%PDF-1.7\n%fake pdf content');
    const r = await salvarPlanta(99, 100, 'pdf', buf);
    expect(r.size_bytes).toBe(buf.length);
    expect(r.hash_sha256.length).toBe(64);
    expect(r.caminho_relativo).toBe('loteamentos/99/quadras/100/planta.pdf');
    const lido = await lerPlanta(99, 100, 'pdf');
    expect(lido.toString()).toBe(buf.toString());
  });

  it('15. salvarPlanta substitui o anterior fazendo backup', async () => {
    const buf1 = Buffer.from('%PDF-1.7\nv1');
    const buf2 = Buffer.from('%PDF-1.7\nv2 different content');
    await salvarPlanta(99, 101, 'pdf', buf1);
    const r2 = await salvarPlanta(99, 101, 'pdf', buf2);
    expect(r2.backup_anterior_path).toBeTruthy();
    expect(r2.backup_anterior_path).toMatch(/_backup_/);
    // O conteudo atual e' o novo
    const atual = await lerPlanta(99, 101, 'pdf');
    expect(atual.toString()).toBe(buf2.toString());
    // E o backup contem o anterior
    expect(fs.existsSync(r2.backup_anterior_path!)).toBe(true);
    const bak = await fs.promises.readFile(r2.backup_anterior_path!);
    expect(bak.toString()).toBe(buf1.toString());
  });

  it('16. removerPlanta retorna true e faz backup', async () => {
    const buf = Buffer.from('%PDF-1.7\nto delete');
    await salvarPlanta(99, 102, 'pdf', buf);
    const r = await removerPlanta(99, 102, 'pdf');
    expect(r).toBe(true);
  });

  it('17. removerPlanta sobre arquivo inexistente retorna false', async () => {
    const r = await removerPlanta(99999, 99999, 'pdf');
    expect(r).toBe(false);
  });

  it('18. salvarPlanta rejeita arquivo invalido (magic byte errado)', async () => {
    const naoPdf = Buffer.from('NAO E PDF');
    await expect(salvarPlanta(99, 103, 'pdf', naoPdf)).rejects.toThrow(/PDF invalido/);
  });
});
